{% set name = "inotify-tools" %}
{% set version = "3.21.9.1" %}
{% set sha256 = "bad96a43b4a417588ec0381e810e5f870044fee437c92d2c2ceaed4b7dd82f38" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rvoicilas/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - automake
    - libtool
    - {{ compiler('c') }}
  host:

test:
  commands:
    - inotifywatch --help || [[ $? == 1 ]]  # --help returns 1
    - inotifywait --help || [[ $? == 1 ]]  # --help returns 1

about:
  home: https://github.com/rvoicilas/inotify-tools
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: This is a package of some commandline utilities relating to inotify.
  description: |
    The general purpose of this package is to allow inotify's features to be
    used from within shell scripts.
  doc_url: https://github.com/rvoicilas/inotify-tools/wiki

extra:
  recipe-maintainers:
    - keuv-grvl
