appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mvCSkBpzNaObFirG4F67PkaNKGSIUU+YvM5jko2e9NYpLDFs2rpwSFn60RzJdcinCJj4/RdS695Hs0vMvmAXqgbsS8ikCc+6JiNefwl96J42mnIdTED7H4tGVH1Y1fEdmVAzYghnz9Reb1WpdaYx/7y/ZeCH7Mz1bF97BHE8r3S4/XXqbTNKLUoJ2S8jcekyWI86ADiq50jrnEQwnZArT8l+mb2tuiy5i1TTTjqAn20XQpDzaqymV9forAvRC9TGEcIoon8s+ZZXRwOimVXWjr4y4aNa4dohsDobanZW1fCowc+k4OaBdjOThBZqMsVwjJ6ltLp6mNgS7EklQJP8qyBwphNxNy3IpPtFdiqmP3mCfuepdpOzLO9FlXVtIfgvp8xXEv3HvuP/LLA91YSTZ869KTevtuNN6+x2mYfyF4hxZKhDcdp/v+FIRjOw2r1MJwlxkq72pGbpTVbbDAIuZ30WaF2Sm9ZbEZ1XoIoZQsUHd4YuO74VgInzAnJGWUMCmtGRvMYtqR0IFmqWaYzUQKRFMElJlqd+8KlzuiL7RyaQQiERXEKNYqy+oETG4aTgWN9L7MXci4rL1AEDghSBCutkjjgQcqdSrVGoiJx25yVoFLUuHkHyQxv6D1Ff5f0VSM43QYbvF1pcMoeKfoygwsXHzZcMwHE0ZOWXFm1IQsc=}
